services:
  mongodb:
    image: mongo:7
    container_name: bezstresowo-mongodb
    environment:
      MONGO_INITDB_DATABASE: bezstresowo
      MONGO_INITDB_ROOT_USERNAME: bezstresowo
      MONGO_INITDB_ROOT_PASSWORD: supersecret
      TZ: Europe/Warsaw
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ['CMD-SHELL', 'mongosh --username $$MONGO_INITDB_ROOT_USERNAME --password $$MONGO_INITDB_ROOT_PASSWORD --eval "db.adminCommand(\"ping\")" --quiet']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: no

volumes:
  mongodb_data:
